[workspace]
channels = ["conda-forge"]
name = "modflow"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.14.*"
flopy = ">=3.10.0,<4"
numpy = ">=2.4.3,<3"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.9,<4"
seaborn = ">=0.13.2,<0.14"
pipx = ">=1.11.2,<2"
